name: 28536 Deploy

on:
  workflow_run:
    workflows: ["28536 Testiranje"]
    types: [completed]
    branches: [main]

jobs:
  docker-build-push:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Checkout kode
      uses: actions/checkout@v4
    
    - name: Prijava v DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.ARDIBYT }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Zgradi in potisni sliko na DockerHub
      uses: docker/build-push-action@v4
      with:
        context: .
        tags: |
          ${{ secrets.ARDIBYT }}/orv-filtri-app:${{ github.sha }}
          ${{ secrets.ARDIBYT }}/orv-filtri-app:latest
        push: true
